name: Deploy Gatsby

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git Credentials
        run: |
          git config --global user.email "${{ github.event.sender.email }}"
          git config --global user.name "${{ github.event.sender.login }}"
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: npm run deploy
